project:
  type: website

website:
  title: "Kendall Keely"
  navbar:
    right:
      - href: about.qmd
        text: About
      - href: work.qmd
        text: Work
      - href: resume.pdf
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css

