project:
  type: website

website:
  title: "Kendall Keely"
  navbar:
    right:
      - href: projects.qmd
        text: Projects
      - href: resume.pdf
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css

